bot_user_id = '@botname:domain.org'
reporting_room_id = '!roomid:domain.org'
admin_room_id = '!adminroomid:domain.org'
approval_emoji = 'â­•'
image_emoji = 'ğŸ“·ï¸'
image_markdown = '> ![]({{file}})'
video_emoji = 'ğŸ“¹ï¸'
video_markdown = '> {{< video src="{{file}}" >}}'
update_config_command = "sh ./update_config.sh"
editors = [
    '@user1:domain.io',
    '@user2:domain.com',
]

[[sections]]
emoji = 'ğŸ”µ'
name = 'core'
title = 'Core Apps and Libraries'
order = 100
usual_reporters = ['@user1:domain.io']

[[sections]]
emoji = 'ğŸ›°ï¸'
name = 'third-party'
title = 'Third Party Projects'
order = 100
usual_reporters = []

[[projects]]
emoji = 'ğŸ“»'
name = 'shortwave'
title = 'Shortwave'
description = 'Internet radio player with over 25000 stations.'
website = 'https://gitlab.gnome.org/World/Shortwave'
default_section = 'circle'
usual_reporters = [
    '@user1:domain.io',
    '@user2:domain.com',
]

[[projects]]
emoji = 'â¬‡ï¸'
name = 'fragments'
title = 'Fragments'
description = 'Easy to use BitTorrent client.'
website = 'https://gitlab.gnome.org/World/Fragments'
default_section = 'circle'
usual_reporters = []
