on:
  push:
    branches: [main]
  pull_request:

name: rustfmt

jobs:
  fmt:
    name: Rustfmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: FrancisRussell/ferrous-actions@v0.1.0-beta.2
        with:
          command: install-rustup
          profile: minimal
      - uses: FrancisRussell/ferrous-actions@v0.1.0-beta.2
        with:
          command: cargo fmt
          args: --all -- --check
